# GitHub Action for generating a contribution graph with a snake eating your contributions. (https://github.com/Platane/snk)

name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake.gif
            dist/github-snake-dark.gif?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: generate snake images"
          commit_user_name: "Angel Aviel Domaoan"
          commit_user_email: "13580338+tenshiAMD@users.noreply.github.com"
          commit_author: "Angel Aviel Domaoan <13580338+tenshiAMD@users.noreply.github.com>"
